-- =========================================================
-- OBS Çekirdeği - Şema
-- PostgreSQL 13+
-- =========================================================
CREATE SCHEMA IF NOT EXISTS obs AUTHORIZATION CURRENT_USER;
SET search_path = obs, public;

-- 1) Referans / sözlük tablosu (dönemler)
CREATE TABLE IF NOT EXISTS donemler (
    donem_kodu   SMALLINT PRIMARY KEY,           -- 1:Güz, 2:Bahar, 3:Yaz
    donem_adi    VARCHAR(20) NOT NULL UNIQUE
);
INSERT INTO donemler(donem_kodu, donem_adi)
VALUES (1,'Güz'),(2,'Bahar'),(3,'Yaz')
ON CONFLICT (donem_kodu) DO NOTHING;

-- 2) Ana tablolar
CREATE TABLE IF NOT EXISTS bolumler (
    bolum_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bolum_kodu   VARCHAR(16) UNIQUE,
    bolum_adi    VARCHAR(120) NOT NULL UNIQUE,
    olusturma_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ogretmenler (
    ogretmen_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad           VARCHAR(60)  NOT NULL,
    soyad        VARCHAR(60)  NOT NULL,
    eposta       VARCHAR(150) UNIQUE,
    bolum_id     BIGINT NOT NULL REFERENCES bolumler(bolum_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    olusturma_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ogrenciler (
    ogrenci_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ogrenci_no   VARCHAR(12) NOT NULL UNIQUE,       -- ör: 202400123
    ad           VARCHAR(60)  NOT NULL,
    soyad        VARCHAR(60)  NOT NULL,
    eposta       VARCHAR(150) UNIQUE,
    baslangic_yili SMALLINT CHECK (baslangic_yili BETWEEN 1990 AND EXTRACT(YEAR FROM NOW())::INT + 1),
    bolum_id     BIGINT NOT NULL REFERENCES bolumler(bolum_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    olusturma_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dersler (
    ders_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ders_kodu    VARCHAR(16) NOT NULL UNIQUE,       -- ör: CENG101
    ders_adi     VARCHAR(160) NOT NULL,
    kredi        SMALLINT NOT NULL CHECK (kredi BETWEEN 1 AND 10),
    bolum_id     BIGINT NOT NULL REFERENCES bolumler(bolum_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    ogretmen_id  BIGINT REFERENCES ogretmenler(ogretmen_id)
                 ON UPDATE CASCADE ON DELETE SET NULL,
    olusturma_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3) İşlemsel tablo: kayıt + notlar
CREATE TABLE IF NOT EXISTS ogrenci_dersleri (
    kayit_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ogrenci_id     BIGINT NOT NULL REFERENCES ogrenciler(ogrenci_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    ders_id        BIGINT NOT NULL REFERENCES dersler(ders_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    yil            SMALLINT NOT NULL CHECK (yil BETWEEN 1990 AND EXTRACT(YEAR FROM NOW())::INT + 1),
    donem_kodu     SMALLINT NOT NULL REFERENCES donemler(donem_kodu)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    vize_notu      NUMERIC(5,2) CHECK (vize_notu BETWEEN 0 AND 100),
    final_notu     NUMERIC(5,2) CHECK (final_notu BETWEEN 0 AND 100),
    olusturma_ts   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ogrenci_id, ders_id, yil, donem_kodu)   -- aynı dönem/kurs için tekrarı engeller
);

-- 4) Konfig: harf notu eşikleri (dahil-hariç)
CREATE TABLE IF NOT EXISTS not_esikleri (
    harf_notu  VARCHAR(2) PRIMARY KEY,             -- AA, BA, ..., FF
    min_puan   NUMERIC(5,2) NOT NULL,              -- alt sınır (dahil)
    max_puan   NUMERIC(5,2) NOT NULL,              -- üst sınır (hariç)
    CHECK (min_puan >= 0 AND max_puan <= 100 AND min_puan < max_puan)
);

-- 5) İndeksler
CREATE INDEX IF NOT EXISTS idx_ogrenciler_no        ON ogrenciler(ogrenci_no);
CREATE INDEX IF NOT EXISTS idx_dersler_kod          ON dersler(ders_kodu);
CREATE INDEX IF NOT EXISTS idx_kayit_ogrenci        ON ogrenci_dersleri(ogrenci_id);
CREATE INDEX IF NOT EXISTS idx_kayit_ders           ON ogrenci_dersleri(ders_id);
CREATE INDEX IF NOT EXISTS idx_kayit_yil_donem      ON ogrenci_dersleri(yil, donem_kodu);
